Update README.md
programminghoch10/Lygisk pull request #22
Opened 2023-02-05 23:06 UTC by binarynoise

add Lygisk vs Magisk

2023-02-06 11:02 UTC, programminghoch10 requested changes

2023-02-06 12:19 UTC, binarynoise commented on README.md
> +
Yes because until a year ago, this feature did not work.
Also this strategy works for migrating Magisk (debug) -> Lygisk.

2023-02-06 12:19 UTC, binarynoise commented on README.md
> +
There are people who need this piece of information explicitly

2023-02-06 12:20 UTC, binarynoise commented on README.md
> +
```suggestion
If you use Lygisk when your storage is not encrypted anyway, it won't give you an advantage.
```

2023-02-06 16:44 UTC, programminghoch10 commented on README.md
> +
```suggestion
If you use Lygisk with unencrypted `/data`, it won't give you any advantages over Magisk.
```

2023-02-06 16:47 UTC, programminghoch10 commented on README.md
> +then reinstalling Lygisk during OTA is automatic.
I don't think the ROM has to have any support for `addon.d`, what would the ROM even do with it?
It only matters that the recovery is actually running `addon.d/*.sh` after install.
This is also why I explicitly wrote `running the LineageOS recovery`.

2023-02-06 16:50 UTC, programminghoch10 commented on README.md
> +
When the feature came to live is irrelevant.
And mentioning this in this way does not convey in any way that Magisk debug migration to Lygisk is possible now. I don't think many people do this exact migration anyways.

2023-02-06 17:23 UTC, binarynoise commented on README.md
> +
Yeah, that's true.

2023-02-06 17:26 UTC, binarynoise commented on README.md
> +
```suggestion
If you use Lygisk with unencrypted `/data`, it won't give you any advantage over Magisk.
```

2023-02-08 19:29 UTC, binarynoise commented on README.md
> +If you have an `addon.d`-compatible ROM (such as LineageOS) with encrypted `/data`, use Lygisk.
```suggestion
If you have an `addon.d`-compatible recovery (such as LineageOS recovery) with encrypted `/data`, use Lygisk.
```

2023-02-09 14:42 UTC, programminghoch10 approved these changes

2023-04-05 19:59 UTC, merged